import {ElementType, PropertySchema} from "@/types/editorElement.type";

export const elementRegistry: Record<ElementType, { complex: boolean }> = {
  button: { complex: true },
  progress_bar: { complex: false },
  checkbox: { complex: false },
  text: { complex: false },
  polygon: { complex: false },
  path: { complex: false },
  rectangle: { complex: false },
  circle: { complex: false },
  line: { complex: false },
  custom: {complex: true},
};


export const basePropertySchema: PropertySchema[] = [
  {
    key: "x",
    label: "Координата X",
    type: "number",
  },
  {
    key: "y",
    label: "Координата Y",
    type: "number",
  },
  {
    key: "w",
    label: "Ширина",
    type: "number",
  },
  {
    key: "h",
    label: "Высота",
    type: "number",
  },
  {
    key: "label",
    label: "Название",
    type: "text",
  },
  {
    key: "rotate",
    label: "Поворот",
    type: "number",
    min: -360,
    max: 360,
    defaultValue: 0,
  },
  // {
  //   key: "scaleX",
  //   label: "Масштаб X",
  //   type: "number",
  //   min: -5,
  //   max: 5,
  //   step: 0.1,
  //   defaultValue: 1,
  // },
  // {
  //   key: "scaleY",
  //   label: "Масштаб Y",
  //   type: "number",
  //   min: -5,
  //   max: 5,
  //   step: 0.1,
  //   defaultValue: 1,
  // },
  // {
  //   key: "flipX",
  //   label: "Отразить по X",
  //   type: "boolean",
  //   defaultValue: false,
  // },
  // {
  //   key: "flipY",
  //   label: "Отразить по Y",
  //   type: "boolean",
  //   defaultValue: false,
  // },
  {
    key: "opacity",
    label: "Прозрачность",
    type: "number",
    min: 0,
    max: 1,
    step: 0.1,
    defaultValue: 1,
  },
];

export const elementPropertyMap: Record<ElementType, PropertySchema[]> = {
  rectangle: [
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина обводки",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
    {
      key: "rx",
      label: "Скругление углов (X)",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
    },
    {
      key: "ry",
      label: "Скругление углов (Y)",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
    },
  ],
  circle: [
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина обводки",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
    {
      key: "rx",
      label: "Горизонтальный радиус",
      type: "number",
      min: 10,
      max: 200,
      defaultValue: 50,
    },
    {
      key: "ry",
      label: "Вертикальный радиус",
      type: "number",
      min: 10,
      max: 200,
      defaultValue: 50,
    },
  ],
  line: [
    {
      key: "strokeColor",
      label: "Цвет линии",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 1,
      max: 20,
      defaultValue: 3,
    },
    {
      key: "strokeDasharray",
      label: "Стиль (пунктир)",
      type: "select",
      options: [
        {label: "Сплошная", value: ""},
        {label: "Пунктир", value: "5 5"},
        {label: "Штрих-пунктир", value: "10 5 2 5"},
      ],
      defaultValue: "",
    },
    {
      key: "arrowEnd",
      label: "Стрелка в конце",
      type: "boolean",
      defaultValue: false,
    },
  ],
  polygon: [
    {
      key: "points",
      label: "Точки (x,y через пробел)",
      type: "text",
      defaultValue: "10,10 90,10 50,90",
    },
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
  ],
  path: [
    {
      key: "d",
      label: "Path (d)",
      type: "text",
      defaultValue: "M10 50 Q50 10 90 50 T90 90",
    },
    {
      key: "bg",
      label: "Заливка",
      type: "color",
      defaultValue: "none",
    },
    {
      key: "strokeColor",
      label: "Цвет линии",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
  ],
  progress_bar: [
    {
      key: "value",
      label: "Значение (%)",
      type: "number",
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 50,
    },
    {
      key: "label",
      label: "Заголовок",
      type: "text",
      defaultValue: "Progress",
    },
    {
      key: "color",
      label: "Цвет полосы",
      type: "color",
      defaultValue: "#3b82f6",
    },
    {
      key: "backgroundColor",
      label: "Цвет фона",
      type: "color",
      defaultValue: "#1e293b",
    },
    {
      key: "strokeColor",
      label: "Цвет рамки",
      type: "color",
      defaultValue: "#475569",
    },
    {
      key: "textColor",
      label: "Цвет текста",
      type: "color",
      defaultValue: "#f8fafc",
    },
    {
      key: "showPercentage",
      label: "Показывать проценты",
      type: "boolean",
      defaultValue: true,
    },
  ],
  checkbox: [
    {
      key: "checked",
      label: "Отмечен",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "label",
      label: "Подпись",
      type: "text",
      defaultValue: "Checkbox",
    },
    {
      key: "color",
      label: "Цвет при отметке",
      type: "color",
      defaultValue: "#3b82f6",
    },
    {
      key: "backgroundColor",
      label: "Цвет фона",
      type: "color",
      defaultValue: "#0f172a",
    },
    {
      key: "strokeColor",
      label: "Цвет рамки",
      type: "color",
      defaultValue: "#94a3b8",
    },
    {
      key: "textColor",
      label: "Цвет текста",
      type: "color",
      defaultValue: "#f1f5f9",
    },
  ],
  text: [
    {
      key: "text",
      label: "Text Content",
      type: "text",
    },
    {
      key: "fontSize",
      label: "Font Size",
      type: "number",
      min: 8,
      max: 72,
      defaultValue: 16,
    },
    {
      key: "color",
      label: "Text Color",
      type: "color",
      defaultValue: "#ffffff",
    },
    {
      key: "bold",
      label: "Bold",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "italic",
      label: "Italic",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "align",
      label: "Text Align",
      type: "select",
      options: [
        {label: "Left", value: "left"},
        {label: "Center", value: "center"},
        {label: "Right", value: "right"},
      ],
      defaultValue: "center",
    },
  ],
  button: [
    {
      key: "color",
      label: "Button Color",
      type: "color",
      defaultValue: "#FF4D4F",
    },
    {
      key: "label",
      label: "Button Label",
      type: "text",
      defaultValue: "Btn",
    },
    {
      key: "textColor",
      label: "Text Color",
      type: "color",
      defaultValue: "#ffffff",
    },
    {
      key: "size",
      label: "Size (px)",
      type: "number",
      min: 30,
      max: 120,
      defaultValue: 50,
    },
    {
      key: "pressed",
      label: "Pressed State (preview)",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "enabled",
      label: "Enabled",
      type: "boolean",
      defaultValue: true,
    },
  ],
  custom: [

  ]
};