import {ElementType, PropertySchema} from "@/types/editorElement.type";

export const elementRegistry: Record<ElementType, { complex: boolean }> = {
  lamp: { complex: true },
  button: { complex: true },
  indicator: { complex: true },
  tank: { complex: true },
  valve: { complex: true },

  numeric: { complex: false },
  text: { complex: false },
  polygon: { complex: false },
  path: { complex: false },
  rectangle: { complex: false },
  circle: { complex: false },
  line: { complex: false },
  custom: {complex: true},
};


export const basePropertySchema: PropertySchema[] = [
  {
    key: "x",
    label: "Координата X",
    type: "number",
  },
  {
    key: "y",
    label: "Координата Y",
    type: "number",
  },
  {
    key: "w",
    label: "Ширина",
    type: "number",
  },
  {
    key: "h",
    label: "Высота",
    type: "number",
  },
  {
    key: "label",
    label: "Название",
    type: "text",
  },
  {
    key: "rotate",
    label: "Поворот",
    type: "number",
    min: -360,
    max: 360,
    defaultValue: 0,
  },
  {
    key: "scaleX",
    label: "Масштаб X",
    type: "number",
    min: -5,
    max: 5,
    step: 0.1,
    defaultValue: 1,
  },
  {
    key: "scaleY",
    label: "Масштаб Y",
    type: "number",
    min: -5,
    max: 5,
    step: 0.1,
    defaultValue: 1,
  },
  {
    key: "flipX",
    label: "Отразить по X",
    type: "boolean",
    defaultValue: false,
  },
  {
    key: "flipY",
    label: "Отразить по Y",
    type: "boolean",
    defaultValue: false,
  },
  {
    key: "opacity",
    label: "Прозрачность",
    type: "number",
    min: 0,
    max: 1,
    step: 0.1,
    defaultValue: 1,
  },
];

export const elementPropertyMap: Record<ElementType, PropertySchema[]> = {
  rectangle: [
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина обводки",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
    {
      key: "rx",
      label: "Скругление углов (X)",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
    },
    {
      key: "ry",
      label: "Скругление углов (Y)",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
    },
  ],
  circle: [
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина обводки",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
    {
      key: "rx",
      label: "Горизонтальный радиус",
      type: "number",
      min: 10,
      max: 200,
      defaultValue: 50,
    },
    {
      key: "ry",
      label: "Вертикальный радиус",
      type: "number",
      min: 10,
      max: 200,
      defaultValue: 50,
    },
  ],
  line: [
    {
      key: "strokeColor",
      label: "Цвет линии",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 1,
      max: 20,
      defaultValue: 3,
    },
    {
      key: "strokeDasharray",
      label: "Стиль (пунктир)",
      type: "select",
      options: [
        {label: "Сплошная", value: ""},
        {label: "Пунктир", value: "5 5"},
        {label: "Штрих-пунктир", value: "10 5 2 5"},
      ],
      defaultValue: "",
    },
    {
      key: "arrowEnd",
      label: "Стрелка в конце",
      type: "boolean",
      defaultValue: false,
    },
  ],
  polygon: [
    {
      key: "points",
      label: "Точки (x,y через пробел)",
      type: "text",
      defaultValue: "10,10 90,10 50,90",
    },
    {
      key: "bg",
      label: "Цвет заливки",
      type: "color",
      defaultValue: "#4b5563",
    },
    {
      key: "strokeColor",
      label: "Цвет обводки",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
  ],
  path: [
    {
      key: "d",
      label: "Path (d)",
      type: "text",
      defaultValue: "M10 50 Q50 10 90 50 T90 90",
    },
    {
      key: "bg",
      label: "Заливка",
      type: "color",
      defaultValue: "none",
    },
    {
      key: "strokeColor",
      label: "Цвет линии",
      type: "color",
      defaultValue: "#9ca3af",
    },
    {
      key: "strokeWidth",
      label: "Толщина",
      type: "number",
      min: 0,
      max: 20,
      defaultValue: 2,
    },
  ],
  valve: [
    {
      key: "status",
      label: "Состояние клапана",
      type: "select",
      options: [
        {label: "Открыт", value: "open"},
        {label: "Закрыт", value: "closed"},
        {label: "Ошибка", value: "error"},
      ],
      defaultValue: "closed",
    },
    {
      key: "label",
      label: "Метка / название",
      type: "text",
      placeholder: "V-101, Клапан 1 и т.д.",
      defaultValue: "",
    },
    {
      key: "colorOpen",
      label: "Цвет при открытом",
      type: "color",
      defaultValue: "#16a34a",
    },
    {
      key: "colorClosed",
      label: "Цвет при закрытом",
      type: "color",
      defaultValue: "#0f172a",
    },
    {
      key: "colorError",
      label: "Цвет при ошибке",
      type: "color",
      defaultValue: "#dc2626",
    },
    {
      key: "size",
      label: "Размер",
      type: "number",
      min: 40,
      max: 200,
      step: 10,
      defaultValue: 80,
    },
  ],
  numeric: [
    {
      key: "value",
      label: "Значение",
      type: "number",
      defaultValue: 0,
    },
    {
      key: "unit",
      label: "Единица измерения",
      type: "text",
      placeholder: "°C, %, bar, кПа и т.д.",
      defaultValue: "",
    },
    {
      key: "precision",
      label: "Знаков после запятой",
      type: "number",
      min: 0,
      max: 6,
      step: 1,
      defaultValue: 2,
    },
    {
      key: "color",
      label: "Цвет значения",
      type: "color",
      defaultValue: "#22d3ee",
    },
    {
      key: "backgroundColor",
      label: "Цвет фона",
      type: "color",
      defaultValue: "#0f172a",
    },
    {
      key: "unitColor",
      label: "Цвет единицы",
      type: "color",
      defaultValue: "#94a3b8",
    },
    // Опционально — если хочешь дать больше контроля
    {
      key: "fontFamily",
      label: "Шрифт",
      type: "select",
      options: [
        {label: "Monospace", value: "monospace"},
        {label: "Inter", value: "Inter, sans-serif"},
        {label: "Arial", value: "Arial, sans-serif"},
      ],
      defaultValue: "monospace",
    },
  ],
  text: [
    {
      key: "text",
      label: "Text Content",
      type: "text",
    },
    {
      key: "fontSize",
      label: "Font Size",
      type: "number",
      min: 8,
      max: 72,
      defaultValue: 16,
    },
    {
      key: "color",
      label: "Text Color",
      type: "color",
      defaultValue: "#ffffff",
    },
    {
      key: "bold",
      label: "Bold",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "italic",
      label: "Italic",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "align",
      label: "Text Align",
      type: "select",
      options: [
        {label: "Left", value: "left"},
        {label: "Center", value: "center"},
        {label: "Right", value: "right"},
      ],
      defaultValue: "center",
    },
  ],
  button: [
    {
      key: "color",
      label: "Button Color",
      type: "color",
      defaultValue: "#FF4D4F",
    },
    {
      key: "label",
      label: "Button Label",
      type: "text",
      defaultValue: "Btn",
    },
    {
      key: "textColor",
      label: "Text Color",
      type: "color",
      defaultValue: "#ffffff",
    },
    {
      key: "size",
      label: "Size (px)",
      type: "number",
      min: 30,
      max: 120,
      defaultValue: 50,
    },
    {
      key: "pressed",
      label: "Pressed State (preview)",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "enabled",
      label: "Enabled",
      type: "boolean",
      defaultValue: true,
    },
  ],
  indicator: [
    {
      key: "status",
      label: "Состояние",
      type: "select",
      options: [
        {label: "Выключен", value: "off"},
        {label: "Включён", value: "on"},
        {label: "Ошибка", value: "error"},
        {label: "Предупреждение", value: "warning"},
      ],
      defaultValue: "off",
    },
    {
      key: "colorOn",
      label: "Цвет включённого",
      type: "color",
      defaultValue: "#00FF00",
    },
    {
      key: "colorOff",
      label: "Цвет выключенного",
      type: "color",
      defaultValue: "#444444",
    },
    {
      key: "colorError",
      label: "Цвет ошибки",
      type: "color",
      defaultValue: "#FF0000",
    },
    {
      key: "colorWarning",
      label: "Цвет предупреждения",
      type: "color",
      defaultValue: "#FFB800",
    },
    {
      key: "glowIntensity",
      label: "Интенсивность свечения",
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.4,
    },
    {
      key: "size",
      label: "Размер",
      type: "number",
      min: 20,
      max: 100,
      step: 5,
      defaultValue: 30,
    },
  ],
  lamp: [
    {
      key: "status",
      label: "Состояние лампы",
      type: "select",
      options: [
        {label: "Выключена", value: "off"},
        {label: "Включена", value: "on"},
        {label: "Мигает", value: "blinking"},
      ],
      defaultValue: "off",
    },
    {
      key: "color",
      label: "Цвет свечения (вкл)",
      type: "color",
      defaultValue: "#FFD700",
    },
    {
      key: "colorOff",
      label: "Цвет выключенной лампы",
      type: "color",
      defaultValue: "#333333",
    },
    {
      key: "glowIntensity",
      label: "Интенсивность свечения",
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.3,
    },
    {
      key: "showBase",
      label: "Показывать цоколь",
      type: "boolean",
      defaultValue: true,
    },
    {
      key: "size",
      label: "Размер",
      type: "number",
      min: 20,
      max: 120,
      step: 5,
      defaultValue: 40,
    },
  ],
  tank: [
    {
      key: "level",
      label: "Fill Level (%)",
      type: "number",
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 60,
    },
    {
      key: "fluidColor",
      label: "Fluid Color",
      type: "color",
      defaultValue: "#3b82f6", // синий по умолчанию
    },
    {
      key: "strokeColor",
      label: "Border Color",
      type: "color",
      defaultValue: "#333333",
    },
    {
      key: "backgroundColor",
      label: "Tank Background",
      type: "color",
      defaultValue: "#e5e7eb", // светло-серый
    },
    {
      key: "showPercentage",
      label: "Show Percentage Text",
      type: "boolean",
      defaultValue: true,
    },
    {
      key: "textColor",
      label: "Percentage Text Color",
      type: "color",
      defaultValue: "#111111",
    },
    {
      key: "scaleLines",
      label: "Show Scale Lines",
      type: "boolean",
      defaultValue: true,
    },
    {
      key: "size",
      label: "Size Preset",
      type: "select",
      options: [
        {label: "Small", value: "small"},
        {label: "Medium", value: "medium"},
        {label: "Large", value: "large"},
      ],
      defaultValue: "medium",
    },
  ],
  custom: [

  ]
};